version: '3'

services:
  storage.api:
    image: storage.api
    build:
      context: ./src/Services/Storage/Storage.API
      dockerfile: Dockerfile

  core.api:
    image: core.api
    build:
      context: ./src/Services/Core/Core.API
      dockerfile: Dockerfile

  element.api:
    image: element.api
    build:
      context: ./src/Services/Element/Element.Api
      dockerfile: Dockerfile
    depends_on:
      - core.api

  riversidecms.mvc:
    image: riversidecms.mvc
    build:
      context: ./src/Applications/RiversideCms.Mvc
      dockerfile: Dockerfile
    depends_on:
      - core.api
      - element.api
