CREATE TABLE [cms].[MasterPage](
	[TenantId] [bigint] NOT NULL,
	[MasterPageId] [bigint] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](256) NOT NULL,
	[PageName] [nvarchar](256) NOT NULL,
	[PageDescription] [nvarchar](max) NULL,
	[AncestorPageId] [bigint] NULL,
	[AncestorPageLevel] [int] NULL,
	[PageType] [int] NOT NULL,
	[HasOccurred] [bit] NOT NULL,
	[HasImage] [bit] NOT NULL,
	[ThumbnailImageWidth] [int] NULL,
	[ThumbnailImageHeight] [int] NULL,
	[ThumbnailImageResizeMode] [int] NULL,
	[PreviewImageWidth] [int] NULL,
	[PreviewImageHeight] [int] NULL,
	[PreviewImageResizeMode] [int] NULL,
	[ImageMinWidth] [int] NULL,
	[ImageMinHeight] [int] NULL,
	[Creatable] [bit] NOT NULL,
	[Deletable] [bit] NOT NULL,
	[Taggable] [bit] NOT NULL,
	[Administration] [bit] NOT NULL,
	[BeginRender] [nvarchar](max) NULL,
	[EndRender] [nvarchar](max) NULL,
 CONSTRAINT [PK_MasterPage] PRIMARY KEY CLUSTERED ([TenantId] ASC, [MasterPageId] ASC),
 CONSTRAINT [FK_MasterPage_Web] FOREIGN KEY([TenantId]) REFERENCES [cms].[Web] ([TenantId])
)