CREATE TABLE [cms].[TemplatePage](
	[TenantId] [bigint] NOT NULL,
	[TemplatePageId] [bigint] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](256) NOT NULL,
	[PageName] [nvarchar](256) NOT NULL,
	[PageDescription] [nvarchar](max) NULL,
	[PageType] [int] NOT NULL,
	[HasOccurred] [bit] NOT NULL,
	[HasImage] [bit] NOT NULL,
	[ThumbnailImageWidth] [int] NULL,
	[ThumbnailImageHeight] [int] NULL,
	[ThumbnailImageResizeMode] [int] NULL,
	[PreviewImageWidth] [int] NULL,
	[PreviewImageHeight] [int] NULL,
	[PreviewImageResizeMode] [int] NULL,
	[ImageMinWidth] [int] NULL,
	[ImageMinHeight] [int] NULL,
	[AncestorPageLevel] [int] NULL,
	[ParentTemplatePageId] [bigint] NULL,
	[ShowOnNavigation] [bit] NOT NULL,
	[Creatable] [bit] NOT NULL,
	[Deletable] [bit] NOT NULL,
	[Taggable] [bit] NOT NULL,
	[Administration] [bit] NOT NULL,
	[BeginRender] [nvarchar](max) NULL,
	[EndRender] [nvarchar](max) NULL,
 CONSTRAINT [PK_TemplatePage] PRIMARY KEY CLUSTERED ([TenantId] ASC, [TemplatePageId] ASC),
 CONSTRAINT [FK_TemplatePage_Template] FOREIGN KEY([TenantId]) REFERENCES [cms].[Template] ([TenantId]),
 CONSTRAINT [FK_TemplatePage_TemplatePage] FOREIGN KEY([TenantId], [ParentTemplatePageId]) REFERENCES [cms].[TemplatePage] ([TenantId], [TemplatePageId])
)