/*----- Empty all tables -----*/

DELETE FROM element.AlbumPhoto
DELETE FROM element.Album
DELETE FROM element.CarouselSlide
DELETE FROM element.CodeSnippet
DELETE FROM element.Contact
DELETE FROM element.Footer
DELETE FROM element.FormField
DELETE FROM element.Form
DELETE FROM element.HtmlUpload
DELETE FROM element.Html
DELETE FROM element.Map
DELETE FROM element.NavBarTab
DELETE FROM element.NavBar
DELETE FROM element.PageHeader
DELETE FROM element.PageList
DELETE FROM element.ForumPost
DELETE FROM element.ForumThread
DELETE FROM element.Forum
DELETE FROM element.TagCloud
DELETE FROM element.LatestThread
DELETE FROM element.Share
DELETE FROM cms.AssetDeployment
DELETE FROM cms.AssetElementType
DELETE FROM cms.Tag
DELETE FROM cms.TagPage
DELETE FROM cms.PageZoneElement
DELETE FROM cms.PageZone
DELETE FROM cms.[Page]
DELETE FROM cms.MasterPageZoneElement
DELETE FROM cms.MasterPageZoneElementType
DELETE FROM cms.MasterPageZone
DELETE FROM cms.MasterPage
DELETE FROM cms.TemplatePageZoneElement
DELETE FROM cms.TemplatePageZoneElementType
DELETE FROM cms.Element
DELETE FROM cms.ElementType
DELETE FROM cms.Domain
DELETE FROM cms.[User]
DELETE FROM cms.[Image]
DELETE FROM cms.[Upload]
DELETE FROM cms.Web
DELETE FROM cms.TemplatePageZone
DELETE FROM cms.TemplatePage
DELETE FROM cms.Template
DELETE FROM cms.Tenant