//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Riverside.Cms.Elements.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ElementResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ElementResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Riverside.Cms.Elements.Resources.ElementResource", typeof(ElementResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update album.
        /// </summary>
        public static string AlbumButtonLabel {
            get {
                return ResourceManager.GetString("AlbumButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string AlbumCancelPhotoButtonLabel {
            get {
                return ResourceManager.GetString("AlbumCancelPhotoButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new photo.
        /// </summary>
        public static string AlbumCreatePhotoButtonLabel {
            get {
                return ResourceManager.GetString("AlbumCreatePhotoButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        public static string AlbumDisplayNameLabel {
            get {
                return ResourceManager.GetString("AlbumDisplayNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name cannot be more than {1} characters..
        /// </summary>
        public static string AlbumDisplayNameMaxLengthMessage {
            get {
                return ResourceManager.GetString("AlbumDisplayNameMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image must be at least {0} by {1} pixels in size..
        /// </summary>
        public static string AlbumImageDimensionsInvalidMessage {
            get {
                return ResourceManager.GetString("AlbumImageDimensionsInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload does not appear to be a valid image..
        /// </summary>
        public static string AlbumImageInvalidMessage {
            get {
                return ResourceManager.GetString("AlbumImageInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo image is required..
        /// </summary>
        public static string AlbumImageRequiredMessage {
            get {
                return ResourceManager.GetString("AlbumImageRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string AlbumPhotoDescriptionLabel {
            get {
                return ResourceManager.GetString("AlbumPhotoDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag to reorder.
        /// </summary>
        public static string AlbumPhotoDragLabel {
            get {
                return ResourceManager.GetString("AlbumPhotoDragLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit album to add photos..
        /// </summary>
        public static string AlbumPhotoEmptyDescription {
            get {
                return ResourceManager.GetString("AlbumPhotoEmptyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album has no photos.
        /// </summary>
        public static string AlbumPhotoEmptyName {
            get {
                return ResourceManager.GetString("AlbumPhotoEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading.
        /// </summary>
        public static string AlbumPhotoNameLabel {
            get {
                return ResourceManager.GetString("AlbumPhotoNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading cannot be more than {1} characters..
        /// </summary>
        public static string AlbumPhotoNameMaxLengthMessage {
            get {
                return ResourceManager.GetString("AlbumPhotoNameMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string AlbumPhotoUploadLabel {
            get {
                return ResourceManager.GetString("AlbumPhotoUploadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update photo.
        /// </summary>
        public static string AlbumUpdatePhotoButtonLabel {
            get {
                return ResourceManager.GetString("AlbumUpdatePhotoButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update breadcrumb navigation.
        /// </summary>
        public static string BreadcrumbNavigationButtonLabel {
            get {
                return ResourceManager.GetString("BreadcrumbNavigationButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page displayed.
        /// </summary>
        public static string BreadcrumbNavigationPageLabel {
            get {
                return ResourceManager.GetString("BreadcrumbNavigationPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update carousel.
        /// </summary>
        public static string CarouselButtonLabel {
            get {
                return ResourceManager.GetString("CarouselButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CarouselCancelSlideButtonLabel {
            get {
                return ResourceManager.GetString("CarouselCancelSlideButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new slide.
        /// </summary>
        public static string CarouselCreateSlideButtonLabel {
            get {
                return ResourceManager.GetString("CarouselCreateSlideButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image must be at least {0} by {1} pixels in size..
        /// </summary>
        public static string CarouselImageDimensionsInvalidMessage {
            get {
                return ResourceManager.GetString("CarouselImageDimensionsInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload does not appear to be a valid image..
        /// </summary>
        public static string CarouselImageInvalidMessage {
            get {
                return ResourceManager.GetString("CarouselImageInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide image is required..
        /// </summary>
        public static string CarouselImageRequiredMessage {
            get {
                return ResourceManager.GetString("CarouselImageRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered button text, but have not specified the page that this text should link to..
        /// </summary>
        public static string CarouselPageRequiredMessage {
            get {
                return ResourceManager.GetString("CarouselPageRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string CarouselSlideDescriptionLabel {
            get {
                return ResourceManager.GetString("CarouselSlideDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag to reorder.
        /// </summary>
        public static string CarouselSlideDragLabel {
            get {
                return ResourceManager.GetString("CarouselSlideDragLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit carousel to add slides..
        /// </summary>
        public static string CarouselSlideEmptyDescription {
            get {
                return ResourceManager.GetString("CarouselSlideEmptyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carousel has no slides.
        /// </summary>
        public static string CarouselSlideEmptyName {
            get {
                return ResourceManager.GetString("CarouselSlideEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading.
        /// </summary>
        public static string CarouselSlideNameLabel {
            get {
                return ResourceManager.GetString("CarouselSlideNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading cannot be more than {1} characters..
        /// </summary>
        public static string CarouselSlideNameMaxLengthMessage {
            get {
                return ResourceManager.GetString("CarouselSlideNameMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select page that button linked to.
        /// </summary>
        public static string CarouselSlidePageDefaultOption {
            get {
                return ResourceManager.GetString("CarouselSlidePageDefaultOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button page.
        /// </summary>
        public static string CarouselSlidePageLabel {
            get {
                return ResourceManager.GetString("CarouselSlidePageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button text.
        /// </summary>
        public static string CarouselSlidePageTextLabel {
            get {
                return ResourceManager.GetString("CarouselSlidePageTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button text cannot be more than {1} characters..
        /// </summary>
        public static string CarouselSlidePageTextMaxLengthMessage {
            get {
                return ResourceManager.GetString("CarouselSlidePageTextMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string CarouselSlideUploadLabel {
            get {
                return ResourceManager.GetString("CarouselSlideUploadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update slide.
        /// </summary>
        public static string CarouselUpdateSlideButtonLabel {
            get {
                return ResourceManager.GetString("CarouselUpdateSlideButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update code snippet.
        /// </summary>
        public static string CodeSnippetButtonLabel {
            get {
                return ResourceManager.GetString("CodeSnippetButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string CodeSnippetCodeLabel {
            get {
                return ResourceManager.GetString("CodeSnippetCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is required.
        /// </summary>
        public static string CodeSnippetCodeRequiredMessage {
            get {
                return ResourceManager.GetString("CodeSnippetCodeRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public class Hello1
        ///{
        ///   public static void Main()
        ///   {
        ///      System.Console.WriteLine(&quot;Hello, World!&quot;);
        ///   }
        ///}.
        /// </summary>
        public static string CodeSnippetDefaultCode {
            get {
                return ResourceManager.GetString("CodeSnippetDefaultCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string CodeSnippetLanguageLabel {
            get {
                return ResourceManager.GetString("CodeSnippetLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string ContactAddressLabel {
            get {
                return ResourceManager.GetString("ContactAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address cannot be more than {1} characters..
        /// </summary>
        public static string ContactAddressMaxLengthMessage {
            get {
                return ResourceManager.GetString("ContactAddressMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update contact details.
        /// </summary>
        public static string ContactButtonLabel {
            get {
                return ResourceManager.GetString("ContactButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        public static string ContactDisplayNameLabel {
            get {
                return ResourceManager.GetString("ContactDisplayNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name cannot be more than {1} characters..
        /// </summary>
        public static string ContactDisplayNameMaxLengthMessage {
            get {
                return ResourceManager.GetString("ContactDisplayNameMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ContactEmailLabel {
            get {
                return ResourceManager.GetString("ContactEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot be more than {1} characters..
        /// </summary>
        public static string ContactEmailMaxLengthMessage {
            get {
                return ResourceManager.GetString("ContactEmailMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string ContactFacebookLabel {
            get {
                return ResourceManager.GetString("ContactFacebookLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook username.
        /// </summary>
        public static string ContactFacebookUsernameLabel {
            get {
                return ResourceManager.GetString("ContactFacebookUsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook username cannot be more than {1} characters..
        /// </summary>
        public static string ContactFacebookUsernameMaxLengthMessage {
            get {
                return ResourceManager.GetString("ContactFacebookUsernameMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram.
        /// </summary>
        public static string ContactInstagramLabel {
            get {
                return ResourceManager.GetString("ContactInstagramLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram username.
        /// </summary>
        public static string ContactInstagramUsernameLabel {
            get {
                return ResourceManager.GetString("ContactInstagramUsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram username cannot be more than {1} characters..
        /// </summary>
        public static string ContactInstagramUsernameMaxLengthMessage {
            get {
                return ResourceManager.GetString("ContactInstagramUsernameMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkedIn company username.
        /// </summary>
        public static string ContactLinkedInCompanyUsernameLabel {
            get {
                return ResourceManager.GetString("ContactLinkedInCompanyUsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkedIn company username cannot be more than {1} characters..
        /// </summary>
        public static string ContactLinkedInCompanyUsernameMaxLengthMessage {
            get {
                return ResourceManager.GetString("ContactLinkedInCompanyUsernameMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkedIn.
        /// </summary>
        public static string ContactLinkedInLabel {
            get {
                return ResourceManager.GetString("ContactLinkedInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkedIn personal username.
        /// </summary>
        public static string ContactLinkedInPersonalUsernameLabel {
            get {
                return ResourceManager.GetString("ContactLinkedInPersonalUsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkedIn personal username cannot be more than {1} characters..
        /// </summary>
        public static string ContactLinkedInPersonalUsernameMaxLengthMessage {
            get {
                return ResourceManager.GetString("ContactLinkedInPersonalUsernameMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preamble.
        /// </summary>
        public static string ContactPreambleLabel {
            get {
                return ResourceManager.GetString("ContactPreambleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone number 1.
        /// </summary>
        public static string ContactTelephoneNumber1Label {
            get {
                return ResourceManager.GetString("ContactTelephoneNumber1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone number 1 cannot be more than {1} characters..
        /// </summary>
        public static string ContactTelephoneNumber1MaxLengthMessage {
            get {
                return ResourceManager.GetString("ContactTelephoneNumber1MaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone number 2.
        /// </summary>
        public static string ContactTelephoneNumber2Label {
            get {
                return ResourceManager.GetString("ContactTelephoneNumber2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone number 2 cannot be more than {1} characters..
        /// </summary>
        public static string ContactTelephoneNumber2MaxLengthMessage {
            get {
                return ResourceManager.GetString("ContactTelephoneNumber2MaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string ContactTwitterLabel {
            get {
                return ResourceManager.GetString("ContactTwitterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter username.
        /// </summary>
        public static string ContactTwitterUsernameLabel {
            get {
                return ResourceManager.GetString("ContactTwitterUsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter username cannot be more than {1} characters..
        /// </summary>
        public static string ContactTwitterUsernameMaxLengthMessage {
            get {
                return ResourceManager.GetString("ContactTwitterUsernameMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTube channel ID.
        /// </summary>
        public static string ContactYouTubeChannelIdLabel {
            get {
                return ResourceManager.GetString("ContactYouTubeChannelIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTube channel ID cannot be more than {1} characters..
        /// </summary>
        public static string ContactYouTubeChannelIdMaxLengthMessage {
            get {
                return ResourceManager.GetString("ContactYouTubeChannelIdMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTube.
        /// </summary>
        public static string ContactYouTubeChannelLabel {
            get {
                return ResourceManager.GetString("ContactYouTubeChannelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current folder.
        /// </summary>
        public static string FolderDefaultOption {
            get {
                return ResourceManager.GetString("FolderDefaultOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update footer.
        /// </summary>
        public static string FooterButtonLabel {
            get {
                return ResourceManager.GetString("FooterButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string FooterMessageLabel {
            get {
                return ResourceManager.GetString("FooterMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add field.
        /// </summary>
        public static string FormAddFieldButtonLabel {
            get {
                return ResourceManager.GetString("FormAddFieldButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update form.
        /// </summary>
        public static string FormButtonLabel {
            get {
                return ResourceManager.GetString("FormButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string FormDefaultFieldLabel {
            get {
                return ResourceManager.GetString("FormDefaultFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send message.
        /// </summary>
        public static string FormDefaultSubmitButtonLabel {
            get {
                return ResourceManager.GetString("FormDefaultSubmitButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks, your message has been sent!.
        /// </summary>
        public static string FormDefaultSubmittedMessage {
            get {
                return ResourceManager.GetString("FormDefaultSubmittedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove field.
        /// </summary>
        public static string FormDeleteFieldButtonLabel {
            get {
                return ResourceManager.GetString("FormDeleteFieldButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following data has been submitted at {0}.
        /// </summary>
        public static string FormEmailHeading {
            get {
                return ResourceManager.GetString("FormEmailHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form submission ({0}).
        /// </summary>
        public static string FormEmailSubject {
            get {
                return ResourceManager.GetString("FormEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New form field.
        /// </summary>
        public static string FormFieldLabelDefaultValue {
            get {
                return ResourceManager.GetString("FormFieldLabelDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FormFieldLabelLabel {
            get {
                return ResourceManager.GetString("FormFieldLabelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field name is required..
        /// </summary>
        public static string FormFieldLabelRequiredMessage {
            get {
                return ResourceManager.GetString("FormFieldLabelRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required?.
        /// </summary>
        public static string FormFieldRequiredLabel {
            get {
                return ResourceManager.GetString("FormFieldRequiredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string FormFieldRequiredMessage {
            get {
                return ResourceManager.GetString("FormFieldRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields.
        /// </summary>
        public static string FormFieldsLabel {
            get {
                return ResourceManager.GetString("FormFieldsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string FormFieldTypeLabel {
            get {
                return ResourceManager.GetString("FormFieldTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple line text field.
        /// </summary>
        public static string FormFieldTypeMultiLineLabel {
            get {
                return ResourceManager.GetString("FormFieldTypeMultiLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single line text field.
        /// </summary>
        public static string FormFieldTypeTextLabel {
            get {
                return ResourceManager.GetString("FormFieldTypeTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient email (one per line).
        /// </summary>
        public static string FormRecipientEmailLabel {
            get {
                return ResourceManager.GetString("FormRecipientEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient email is required..
        /// </summary>
        public static string FormRecipientEmailRequiredMessage {
            get {
                return ResourceManager.GetString("FormRecipientEmailRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit button text.
        /// </summary>
        public static string FormSubmitButtonLabelLabel {
            get {
                return ResourceManager.GetString("FormSubmitButtonLabelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit button text cannot be more than {1} characters..
        /// </summary>
        public static string FormSubmitButtonLabelMaxLengthMessage {
            get {
                return ResourceManager.GetString("FormSubmitButtonLabelMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit button text is required..
        /// </summary>
        public static string FormSubmitButtonLabelRequiredMessage {
            get {
                return ResourceManager.GetString("FormSubmitButtonLabelRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message displayed after form submitted.
        /// </summary>
        public static string FormSubmittedMessageLabel {
            get {
                return ResourceManager.GetString("FormSubmittedMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted message is required..
        /// </summary>
        public static string FormSubmittedMessageRequiredMessage {
            get {
                return ResourceManager.GetString("FormSubmittedMessageRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all comments.
        /// </summary>
        public static string ForumAllThreadsLabel {
            get {
                return ResourceManager.GetString("ForumAllThreadsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello %ALIAS%!&lt;br/&gt;&lt;br/&gt;
        ///
        ///%POSTALIAS% has replied to your comment entitled %THREADSUBJECT%&lt;br/&gt;&lt;br/&gt;
        ///
        ///Click the link below to view the reply.&lt;br/&gt;&lt;br/&gt;
        ///
        ///&lt;a href=&quot;%FORUMURL%&quot;&gt;%FORUMURL%&lt;/a&gt;&lt;br/&gt;&lt;br/&gt;
        ///
        ///Thanks!.
        /// </summary>
        public static string ForumCreatePostEmailHtmlBody {
            get {
                return ResourceManager.GetString("ForumCreatePostEmailHtmlBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello %ALIAS%!
        ///
        ///%POSTALIAS% has replied to your comment entitled %THREADSUBJECT%
        ///
        ///Click the link below to view the reply.
        ///
        ///%FORUMURL%
        ///
        ///Thanks!.
        /// </summary>
        public static string ForumCreatePostEmailPlainTextBody {
            get {
                return ResourceManager.GetString("ForumCreatePostEmailPlainTextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %POSTALIAS% has replied to your comment entitled %THREADSUBJECT%.
        /// </summary>
        public static string ForumCreatePostEmailSubject {
            get {
                return ResourceManager.GetString("ForumCreatePostEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new comment.
        /// </summary>
        public static string ForumCreateThreadButtonLabel {
            get {
                return ResourceManager.GetString("ForumCreateThreadButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new comment.
        /// </summary>
        public static string ForumCreateThreadLinkLabel {
            get {
                return ResourceManager.GetString("ForumCreateThreadLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete comment.
        /// </summary>
        public static string ForumDeleteThreadButtonLabel {
            get {
                return ResourceManager.GetString("ForumDeleteThreadButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ForumDeleteThreadOptionLabel {
            get {
                return ResourceManager.GetString("ForumDeleteThreadOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string ForumMessageLabel {
            get {
                return ResourceManager.GetString("ForumMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment is required..
        /// </summary>
        public static string ForumMessageRequiredMessage {
            get {
                return ResourceManager.GetString("ForumMessageRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why don&apos;t you add one?.
        /// </summary>
        public static string ForumNoThreadsCreateThreadLabel {
            get {
                return ResourceManager.GetString("ForumNoThreadsCreateThreadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This forum has no comments..
        /// </summary>
        public static string ForumNoThreadsMessage {
            get {
                return ResourceManager.GetString("ForumNoThreadsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify me when others reply to my comment?.
        /// </summary>
        public static string ForumNotifyLabel {
            get {
                return ResourceManager.GetString("ForumNotifyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string ForumPageLabel {
            get {
                return ResourceManager.GetString("ForumPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted by.
        /// </summary>
        public static string ForumPostedByLabel {
            get {
                return ResourceManager.GetString("ForumPostedByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Originally Posted By {0}**.
        /// </summary>
        public static string ForumQuoteBegin {
            get {
                return ResourceManager.GetString("ForumQuoteBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote comment.
        /// </summary>
        public static string ForumQuotePostButtonLabel {
            get {
                return ResourceManager.GetString("ForumQuotePostButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.
        /// </summary>
        public static string ForumQuotePostOptionLabel {
            get {
                return ResourceManager.GetString("ForumQuotePostOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote comment.
        /// </summary>
        public static string ForumQuoteThreadButtonLabel {
            get {
                return ResourceManager.GetString("ForumQuoteThreadButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.
        /// </summary>
        public static string ForumQuoteThreadOptionLabel {
            get {
                return ResourceManager.GetString("ForumQuoteThreadOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply to comment.
        /// </summary>
        public static string ForumReplyPostButtonLabel {
            get {
                return ResourceManager.GetString("ForumReplyPostButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string ForumReplyPostOptionLabel {
            get {
                return ResourceManager.GetString("ForumReplyPostOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply to comment.
        /// </summary>
        public static string ForumReplyThreadButtonLabel {
            get {
                return ResourceManager.GetString("ForumReplyThreadButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why don&apos;t you create one?.
        /// </summary>
        public static string ForumReplyThreadMessage {
            get {
                return ResourceManager.GetString("ForumReplyThreadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string ForumReplyThreadOptionLabel {
            get {
                return ResourceManager.GetString("ForumReplyThreadOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string ForumSubjectLabel {
            get {
                return ResourceManager.GetString("ForumSubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject cannot be more than {1} characters..
        /// </summary>
        public static string ForumSubjectMaxLengthMessage {
            get {
                return ResourceManager.GetString("ForumSubjectMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject is required..
        /// </summary>
        public static string ForumSubjectRequiredMessage {
            get {
                return ResourceManager.GetString("ForumSubjectRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This comment has no replies..
        /// </summary>
        public static string ForumThreadNoRepliesMessage {
            get {
                return ResourceManager.GetString("ForumThreadNoRepliesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        public static string ForumThreadsCreatedColumnLabel {
            get {
                return ResourceManager.GetString("ForumThreadsCreatedColumnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Post.
        /// </summary>
        public static string ForumThreadsLastPostColumnLabel {
            get {
                return ResourceManager.GetString("ForumThreadsLastPostColumnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replies.
        /// </summary>
        public static string ForumThreadsRepliesColumnLabel {
            get {
                return ResourceManager.GetString("ForumThreadsRepliesColumnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string ForumThreadsSubjectColumnLabel {
            get {
                return ResourceManager.GetString("ForumThreadsSubjectColumnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string ForumThreadsViewsColumnLabel {
            get {
                return ResourceManager.GetString("ForumThreadsViewsColumnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update comment.
        /// </summary>
        public static string ForumUpdatePostButtonLabel {
            get {
                return ResourceManager.GetString("ForumUpdatePostButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string ForumUpdatePostOptionLabel {
            get {
                return ResourceManager.GetString("ForumUpdatePostOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update comment.
        /// </summary>
        public static string ForumUpdateThreadButtonLabel {
            get {
                return ResourceManager.GetString("ForumUpdateThreadButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string ForumUpdateThreadOptionLabel {
            get {
                return ResourceManager.GetString("ForumUpdateThreadOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update text.
        /// </summary>
        public static string HtmlButtonLabel {
            get {
                return ResourceManager.GetString("HtmlButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod?&lt;/p&gt;.
        /// </summary>
        public static string HtmlDefaultHtml {
            get {
                return ResourceManager.GetString("HtmlDefaultHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string HtmlHtmlLabel {
            get {
                return ResourceManager.GetString("HtmlHtmlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload does not appear to be a valid image..
        /// </summary>
        public static string HtmlImageInvalidMessage {
            get {
                return ResourceManager.GetString("HtmlImageInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload image or file.
        /// </summary>
        public static string HtmlUploadLabel {
            get {
                return ResourceManager.GetString("HtmlUploadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update latest comments.
        /// </summary>
        public static string LatestThreadButtonLabel {
            get {
                return ResourceManager.GetString("LatestThreadButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        public static string LatestThreadDisplayNameLabel {
            get {
                return ResourceManager.GetString("LatestThreadDisplayNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name cannot be more than {1} characters..
        /// </summary>
        public static string LatestThreadDisplayNameMaxLengthMessage {
            get {
                return ResourceManager.GetString("LatestThreadDisplayNameMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message displayed when no threads found.
        /// </summary>
        public static string LatestThreadNoThreadsMessageLabel {
            get {
                return ResourceManager.GetString("LatestThreadNoThreadsMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No threads message is required..
        /// </summary>
        public static string LatestThreadNoThreadsMessageRequiredMessage {
            get {
                return ResourceManager.GetString("LatestThreadNoThreadsMessageRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show threads of pages in this folder.
        /// </summary>
        public static string LatestThreadPageLabel {
            get {
                return ResourceManager.GetString("LatestThreadPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of threads displayed.
        /// </summary>
        public static string LatestThreadPageSizeLabel {
            get {
                return ResourceManager.GetString("LatestThreadPageSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size is required..
        /// </summary>
        public static string LatestThreadPageSizeRequiredMessage {
            get {
                return ResourceManager.GetString("LatestThreadPageSizeRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preamble.
        /// </summary>
        public static string LatestThreadPreambleLabel {
            get {
                return ResourceManager.GetString("LatestThreadPreambleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursively show threads of all child pages?.
        /// </summary>
        public static string LatestThreadRecursiveLabel {
            get {
                return ResourceManager.GetString("LatestThreadRecursiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update map.
        /// </summary>
        public static string MapButtonLabel {
            get {
                return ResourceManager.GetString("MapButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        public static string MapDisplayNameLabel {
            get {
                return ResourceManager.GetString("MapDisplayNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name cannot be more than {1} characters..
        /// </summary>
        public static string MapDisplayNameMaxLengthMessage {
            get {
                return ResourceManager.GetString("MapDisplayNameMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude is invalid..
        /// </summary>
        public static string MapLatitudeInvalidMessage {
            get {
                return ResourceManager.GetString("MapLatitudeInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string MapLatitudeLabel {
            get {
                return ResourceManager.GetString("MapLatitudeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude cannot be more than {1} characters..
        /// </summary>
        public static string MapLatitudeMaxLengthMessage {
            get {
                return ResourceManager.GetString("MapLatitudeMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude is required..
        /// </summary>
        public static string MapLatitudeRequiredMessage {
            get {
                return ResourceManager.GetString("MapLatitudeRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude is invalid..
        /// </summary>
        public static string MapLongitudeInvalidMessage {
            get {
                return ResourceManager.GetString("MapLongitudeInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string MapLongitudeLabel {
            get {
                return ResourceManager.GetString("MapLongitudeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude cannot be more than {1} characters..
        /// </summary>
        public static string MapLongitudeMaxLengthMessage {
            get {
                return ResourceManager.GetString("MapLongitudeMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude is required..
        /// </summary>
        public static string MapLongitudeRequiredMessage {
            get {
                return ResourceManager.GetString("MapLongitudeRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tab.
        /// </summary>
        public static string NavBarAddTabButtonLabel {
            get {
                return ResourceManager.GetString("NavBarAddTabButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update navigation bar.
        /// </summary>
        public static string NavBarButtonLabel {
            get {
                return ResourceManager.GetString("NavBarButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove tab.
        /// </summary>
        public static string NavBarDeleteTabButtonLabel {
            get {
                return ResourceManager.GetString("NavBarDeleteTabButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site name.
        /// </summary>
        public static string NavBarNameLabel {
            get {
                return ResourceManager.GetString("NavBarNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string NavBarPageLabel {
            get {
                return ResourceManager.GetString("NavBarPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NavBarTabNameLabel {
            get {
                return ResourceManager.GetString("NavBarTabNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be more than {1} characters..
        /// </summary>
        public static string NavBarTabNameMaxLengthMessage {
            get {
                return ResourceManager.GetString("NavBarTabNameMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string NavBarTabNameRequiredMessage {
            get {
                return ResourceManager.GetString("NavBarTabNameRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page is required..
        /// </summary>
        public static string NavBarTabPageRequiredMessage {
            get {
                return ResourceManager.GetString("NavBarTabPageRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabs.
        /// </summary>
        public static string NavBarTabsLabel {
            get {
                return ResourceManager.GetString("NavBarTabsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle navigation.
        /// </summary>
        public static string NavBarToggleNavigationLabel {
            get {
                return ResourceManager.GetString("NavBarToggleNavigationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current page.
        /// </summary>
        public static string PageDefaultOption {
            get {
                return ResourceManager.GetString("PageDefaultOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update page header.
        /// </summary>
        public static string PageHeaderButtonLabel {
            get {
                return ResourceManager.GetString("PageHeaderButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted.
        /// </summary>
        public static string PageHeaderCreatedLabel {
            get {
                return ResourceManager.GetString("PageHeaderCreatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string PageHeaderHomeBreadcrumbLabel {
            get {
                return ResourceManager.GetString("PageHeaderHomeBreadcrumbLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs.
        /// </summary>
        public static string PageHeaderOccurredFutureLabel {
            get {
                return ResourceManager.GetString("PageHeaderOccurredFutureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurred.
        /// </summary>
        public static string PageHeaderOccurredPastLabel {
            get {
                return ResourceManager.GetString("PageHeaderOccurredPastLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page displayed.
        /// </summary>
        public static string PageHeaderPageLabel {
            get {
                return ResourceManager.GetString("PageHeaderPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show breadcrumbs?.
        /// </summary>
        public static string PageHeaderShowBreadcrumbsLabel {
            get {
                return ResourceManager.GetString("PageHeaderShowBreadcrumbsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show page created date?.
        /// </summary>
        public static string PageHeaderShowCreatedLabel {
            get {
                return ResourceManager.GetString("PageHeaderShowCreatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show page description?.
        /// </summary>
        public static string PageHeaderShowDescriptionLabel {
            get {
                return ResourceManager.GetString("PageHeaderShowDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show page image?.
        /// </summary>
        public static string PageHeaderShowImageLabel {
            get {
                return ResourceManager.GetString("PageHeaderShowImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show page name?.
        /// </summary>
        public static string PageHeaderShowNameLabel {
            get {
                return ResourceManager.GetString("PageHeaderShowNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show page occurred date?.
        /// </summary>
        public static string PageHeaderShowOccurredLabel {
            get {
                return ResourceManager.GetString("PageHeaderShowOccurredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show page last updated date?.
        /// </summary>
        public static string PageHeaderShowUpdatedLabel {
            get {
                return ResourceManager.GetString("PageHeaderShowUpdatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string PageHeaderUpdatedLabel {
            get {
                return ResourceManager.GetString("PageHeaderUpdatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update page list.
        /// </summary>
        public static string PageListButtonLabel {
            get {
                return ResourceManager.GetString("PageListButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string PageListCommentsLabel {
            get {
                return ResourceManager.GetString("PageListCommentsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted.
        /// </summary>
        public static string PageListCreatedLabel {
            get {
                return ResourceManager.GetString("PageListCreatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        public static string PageListDisplayNameLabel {
            get {
                return ResourceManager.GetString("PageListDisplayNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name cannot be more than {1} characters..
        /// </summary>
        public static string PageListDisplayNameMaxLengthMessage {
            get {
                return ResourceManager.GetString("PageListDisplayNameMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More pages message.
        /// </summary>
        public static string PageListMoreMessageLabel {
            get {
                return ResourceManager.GetString("PageListMoreMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More message cannot be more than {1} characters..
        /// </summary>
        public static string PageListMoreMessageMaxLengthMessage {
            get {
                return ResourceManager.GetString("PageListMoreMessageMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message displayed when no pages found.
        /// </summary>
        public static string PageListNoPagesMessageLabel {
            get {
                return ResourceManager.GetString("PageListNoPagesMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs.
        /// </summary>
        public static string PageListOccurredFutureLabel {
            get {
                return ResourceManager.GetString("PageListOccurredFutureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurred.
        /// </summary>
        public static string PageListOccurredPastLabel {
            get {
                return ResourceManager.GetString("PageListOccurredPastLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List pages in this folder.
        /// </summary>
        public static string PageListPageLabel {
            get {
                return ResourceManager.GetString("PageListPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of pages displayed.
        /// </summary>
        public static string PageListPageSizeLabel {
            get {
                return ResourceManager.GetString("PageListPageSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size must be between {1} and {2} pixels..
        /// </summary>
        public static string PageListPageSizeRangeMessage {
            get {
                return ResourceManager.GetString("PageListPageSizeRangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size is required..
        /// </summary>
        public static string PageListPageSizeRequiredMessage {
            get {
                return ResourceManager.GetString("PageListPageSizeRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of page listed.
        /// </summary>
        public static string PageListPageTypeLabel {
            get {
                return ResourceManager.GetString("PageListPageTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page type is required..
        /// </summary>
        public static string PageListPageTypeRequiredMessage {
            get {
                return ResourceManager.GetString("PageListPageTypeRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preamble.
        /// </summary>
        public static string PageListPreambleLabel {
            get {
                return ResourceManager.GetString("PageListPreambleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursively list all child pages?.
        /// </summary>
        public static string PageListRecursiveLabel {
            get {
                return ResourceManager.GetString("PageListRecursiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show page image as background?.
        /// </summary>
        public static string PageListShowBackgroundImageLabel {
            get {
                return ResourceManager.GetString("PageListShowBackgroundImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show page comments?.
        /// </summary>
        public static string PageListShowCommentsLabel {
            get {
                return ResourceManager.GetString("PageListShowCommentsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show page created date?.
        /// </summary>
        public static string PageListShowCreatedLabel {
            get {
                return ResourceManager.GetString("PageListShowCreatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show page description?.
        /// </summary>
        public static string PageListShowDescriptionLabel {
            get {
                return ResourceManager.GetString("PageListShowDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show page image?.
        /// </summary>
        public static string PageListShowImageLabel {
            get {
                return ResourceManager.GetString("PageListShowImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show page occurred date?.
        /// </summary>
        public static string PageListShowOccurredLabel {
            get {
                return ResourceManager.GetString("PageListShowOccurredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show pager when number of pages greater than page size?.
        /// </summary>
        public static string PageListShowPagerLabel {
            get {
                return ResourceManager.GetString("PageListShowPagerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show pages related to the current page?.
        /// </summary>
        public static string PageListShowRelatedLabel {
            get {
                return ResourceManager.GetString("PageListShowRelatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show page tags?.
        /// </summary>
        public static string PageListShowTagsLabel {
            get {
                return ResourceManager.GetString("PageListShowTagsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show page last updated date?.
        /// </summary>
        public static string PageListShowUpdatedLabel {
            get {
                return ResourceManager.GetString("PageListShowUpdatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string PageListSortAscendingOption {
            get {
                return ResourceManager.GetString("PageListSortAscendingOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort direction.
        /// </summary>
        public static string PageListSortAscLabel {
            get {
                return ResourceManager.GetString("PageListSortAscLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort direction is required..
        /// </summary>
        public static string PageListSortAscRequiredMessage {
            get {
                return ResourceManager.GetString("PageListSortAscRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order pages by.
        /// </summary>
        public static string PageListSortByLabel {
            get {
                return ResourceManager.GetString("PageListSortByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page order is required..
        /// </summary>
        public static string PageListSortByRequiredMessage {
            get {
                return ResourceManager.GetString("PageListSortByRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string PageListSortDescendingOption {
            get {
                return ResourceManager.GetString("PageListSortDescendingOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string PageListUpdatedLabel {
            get {
                return ResourceManager.GetString("PageListUpdatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update share.
        /// </summary>
        public static string ShareButtonLabel {
            get {
                return ResourceManager.GetString("ShareButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on Digg.
        /// </summary>
        public static string ShareDiggTooltip {
            get {
                return ResourceManager.GetString("ShareDiggTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        public static string ShareDisplayNameLabel {
            get {
                return ResourceManager.GetString("ShareDisplayNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name cannot be more than {1} characters..
        /// </summary>
        public static string ShareDisplayNameMaxLengthMessage {
            get {
                return ResourceManager.GetString("ShareDisplayNameMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on Facebook.
        /// </summary>
        public static string ShareFacebookTooltip {
            get {
                return ResourceManager.GetString("ShareFacebookTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on Google.
        /// </summary>
        public static string ShareGoogleTooltip {
            get {
                return ResourceManager.GetString("ShareGoogleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on LinkedIn.
        /// </summary>
        public static string ShareLinkedInTooltip {
            get {
                return ResourceManager.GetString("ShareLinkedInTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on Pinterest.
        /// </summary>
        public static string SharePinterestTooltip {
            get {
                return ResourceManager.GetString("SharePinterestTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on Reddit.
        /// </summary>
        public static string ShareRedditTooltip {
            get {
                return ResourceManager.GetString("ShareRedditTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on Digg?.
        /// </summary>
        public static string ShareShareOnDiggLabel {
            get {
                return ResourceManager.GetString("ShareShareOnDiggLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on Facebook?.
        /// </summary>
        public static string ShareShareOnFacebookLabel {
            get {
                return ResourceManager.GetString("ShareShareOnFacebookLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on Google?.
        /// </summary>
        public static string ShareShareOnGoogleLabel {
            get {
                return ResourceManager.GetString("ShareShareOnGoogleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on LinkedIn?.
        /// </summary>
        public static string ShareShareOnLinkedInLabel {
            get {
                return ResourceManager.GetString("ShareShareOnLinkedInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on Pinterest?.
        /// </summary>
        public static string ShareShareOnPinterestLabel {
            get {
                return ResourceManager.GetString("ShareShareOnPinterestLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on Reddit?.
        /// </summary>
        public static string ShareShareOnRedditLabel {
            get {
                return ResourceManager.GetString("ShareShareOnRedditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on StumbleUpon?.
        /// </summary>
        public static string ShareShareOnStumbleUponLabel {
            get {
                return ResourceManager.GetString("ShareShareOnStumbleUponLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on Tumblr?.
        /// </summary>
        public static string ShareShareOnTumblrLabel {
            get {
                return ResourceManager.GetString("ShareShareOnTumblrLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on Twitter?.
        /// </summary>
        public static string ShareShareOnTwitterLabel {
            get {
                return ResourceManager.GetString("ShareShareOnTwitterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on StumbleUpon.
        /// </summary>
        public static string ShareStumbleUponTooltip {
            get {
                return ResourceManager.GetString("ShareStumbleUponTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on Tumblr.
        /// </summary>
        public static string ShareTumblrTooltip {
            get {
                return ResourceManager.GetString("ShareTumblrTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on Twitter.
        /// </summary>
        public static string ShareTwitterTooltip {
            get {
                return ResourceManager.GetString("ShareTwitterTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show log in and register user options?.
        /// </summary>
        public static string ShowLoggedOffUserOptionsLabel {
            get {
                return ResourceManager.GetString("ShowLoggedOffUserOptionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show update profile, change password and log out user options?.
        /// </summary>
        public static string ShowLoggedOnUserOptionsLabel {
            get {
                return ResourceManager.GetString("ShowLoggedOnUserOptionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update table details.
        /// </summary>
        public static string TableButtonLabel {
            get {
                return ResourceManager.GetString("TableButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        public static string TableDisplayNameLabel {
            get {
                return ResourceManager.GetString("TableDisplayNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name cannot be more than {1} characters..
        /// </summary>
        public static string TableDisplayNameMaxLengthMessage {
            get {
                return ResourceManager.GetString("TableDisplayNameMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preamble.
        /// </summary>
        public static string TablePreambleLabel {
            get {
                return ResourceManager.GetString("TablePreambleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data (comma separated values, 1 line per row).
        /// </summary>
        public static string TableRowsLabel {
            get {
                return ResourceManager.GetString("TableRowsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show column headers (use first line of data)?.
        /// </summary>
        public static string TableShowHeadersLabel {
            get {
                return ResourceManager.GetString("TableShowHeadersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update tag cloud.
        /// </summary>
        public static string TagCloudButtonLabel {
            get {
                return ResourceManager.GetString("TagCloudButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tags found..
        /// </summary>
        public static string TagCloudDefaultNoTagsMessage {
            get {
                return ResourceManager.GetString("TagCloudDefaultNoTagsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        public static string TagCloudDisplayNameLabel {
            get {
                return ResourceManager.GetString("TagCloudDisplayNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name cannot be more than {1} characters..
        /// </summary>
        public static string TagCloudDisplayNameMaxLengthMessage {
            get {
                return ResourceManager.GetString("TagCloudDisplayNameMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message displayed when no tags found.
        /// </summary>
        public static string TagCloudNoTagsMessageLabel {
            get {
                return ResourceManager.GetString("TagCloudNoTagsMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tags message is required..
        /// </summary>
        public static string TagCloudNoTagsMessageRequiredMessage {
            get {
                return ResourceManager.GetString("TagCloudNoTagsMessageRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tags of pages in this folder.
        /// </summary>
        public static string TagCloudPageLabel {
            get {
                return ResourceManager.GetString("TagCloudPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursively show tags of all child pages?.
        /// </summary>
        public static string TagCloudRecursiveLabel {
            get {
                return ResourceManager.GetString("TagCloudRecursiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TestimonalCancelButtonLabel {
            get {
                return ResourceManager.GetString("TestimonalCancelButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string TestimonialAuthorLabel {
            get {
                return ResourceManager.GetString("TestimonialAuthorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author cannot be more than {1} characters..
        /// </summary>
        public static string TestimonialAuthorMaxLengthMessage {
            get {
                return ResourceManager.GetString("TestimonialAuthorMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author is required..
        /// </summary>
        public static string TestimonialAuthorRequiredMessage {
            get {
                return ResourceManager.GetString("TestimonialAuthorRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author&apos;s title.
        /// </summary>
        public static string TestimonialAuthorTitleLabel {
            get {
                return ResourceManager.GetString("TestimonialAuthorTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author&apos;s title cannot be more than {1} characters..
        /// </summary>
        public static string TestimonialAuthorTitleMaxLengthMessage {
            get {
                return ResourceManager.GetString("TestimonialAuthorTitleMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testimonial date.
        /// </summary>
        public static string TestimonialCommentDateLabel {
            get {
                return ResourceManager.GetString("TestimonialCommentDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testimonial date cannot be more than {1} characters..
        /// </summary>
        public static string TestimonialCommentDateMaxLengthMessage {
            get {
                return ResourceManager.GetString("TestimonialCommentDateMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag to reorder.
        /// </summary>
        public static string TestimonialCommentDragLabel {
            get {
                return ResourceManager.GetString("TestimonialCommentDragLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No testimonials found. Edit testimonial to add some!.
        /// </summary>
        public static string TestimonialCommentEmptyName {
            get {
                return ResourceManager.GetString("TestimonialCommentEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testimonial.
        /// </summary>
        public static string TestimonialCommentLabel {
            get {
                return ResourceManager.GetString("TestimonialCommentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testimonial is required..
        /// </summary>
        public static string TestimonialCommentRequiredMessage {
            get {
                return ResourceManager.GetString("TestimonialCommentRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add testimonial.
        /// </summary>
        public static string TestimonialCreateButtonLabel {
            get {
                return ResourceManager.GetString("TestimonialCreateButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add testimonial.
        /// </summary>
        public static string TestimonialCreateCommentButtonLabel {
            get {
                return ResourceManager.GetString("TestimonialCreateCommentButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John Smith.
        /// </summary>
        public static string TestimonialDefaultAuthor {
            get {
                return ResourceManager.GetString("TestimonialDefaultAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEO of John Smith Industries Limited.
        /// </summary>
        public static string TestimonialDefaultAuthorTitle {
            get {
                return ResourceManager.GetString("TestimonialDefaultAuthorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am very impressed with the level of service offered by Acme Corporation..
        /// </summary>
        public static string TestimonialDefaultComment {
            get {
                return ResourceManager.GetString("TestimonialDefaultComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10th December 2016.
        /// </summary>
        public static string TestimonialDefaultCommentDate {
            get {
                return ResourceManager.GetString("TestimonialDefaultCommentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        public static string TestimonialDisplayNameLabel {
            get {
                return ResourceManager.GetString("TestimonialDisplayNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name cannot be more than {1} characters..
        /// </summary>
        public static string TestimonialDisplayNameMaxLengthMessage {
            get {
                return ResourceManager.GetString("TestimonialDisplayNameMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preamble.
        /// </summary>
        public static string TestimonialPreambleLabel {
            get {
                return ResourceManager.GetString("TestimonialPreambleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update testimonials.
        /// </summary>
        public static string TestimonialUpdateButtonLabel {
            get {
                return ResourceManager.GetString("TestimonialUpdateButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update testimonial.
        /// </summary>
        public static string TestimonialUpdateCommentButtonLabel {
            get {
                return ResourceManager.GetString("TestimonialUpdateCommentButtonLabel", resourceCulture);
            }
        }
    }
}
