//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Riverside.Cms.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdministrationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdministrationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Riverside.Cms.Core.Resources.AdministrationResource", typeof(AdministrationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        public static string ChangePasswordLabel {
            get {
                return ResourceManager.GetString("ChangePasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the form below to create a new master page..
        /// </summary>
        public static string CreateMasterPageDescription {
            get {
                return ResourceManager.GetString("CreateMasterPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create master page.
        /// </summary>
        public static string CreateMasterPageName {
            get {
                return ResourceManager.GetString("CreateMasterPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master page.
        /// </summary>
        public static string CreateMasterPageOptionLabel {
            get {
                return ResourceManager.GetString("CreateMasterPageOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new master page.
        /// </summary>
        public static string CreateMasterPageSectionLabel {
            get {
                return ResourceManager.GetString("CreateMasterPageSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the form below to create a new {0}..
        /// </summary>
        public static string CreatePageDescription {
            get {
                return ResourceManager.GetString("CreatePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create {0}.
        /// </summary>
        public static string CreatePageName {
            get {
                return ResourceManager.GetString("CreatePageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string CreatePageOptionLabel {
            get {
                return ResourceManager.GetString("CreatePageOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new page.
        /// </summary>
        public static string CreatePageSectionLabel {
            get {
                return ResourceManager.GetString("CreatePageSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string CreateUserLabel {
            get {
                return ResourceManager.GetString("CreateUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts and colours.
        /// </summary>
        public static string FontsAndColoursOptionLabel {
            get {
                return ResourceManager.GetString("FontsAndColoursOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten password.
        /// </summary>
        public static string ForgottenPasswordLabel {
            get {
                return ResourceManager.GetString("ForgottenPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string HamburgerAccountLabel {
            get {
                return ResourceManager.GetString("HamburgerAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domains.
        /// </summary>
        public static string HamburgerDomainsLabel {
            get {
                return ResourceManager.GetString("HamburgerDomainsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layouts.
        /// </summary>
        public static string HamburgerLayoutsLabel {
            get {
                return ResourceManager.GetString("HamburgerLayoutsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string HamburgerPagesLabel {
            get {
                return ResourceManager.GetString("HamburgerPagesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string HamburgerUsersLabel {
            get {
                return ResourceManager.GetString("HamburgerUsersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Websites.
        /// </summary>
        public static string HamburgerWebsitesLabel {
            get {
                return ResourceManager.GetString("HamburgerWebsitesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zones.
        /// </summary>
        public static string HamburgerZonesLabel {
            get {
                return ResourceManager.GetString("HamburgerZonesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Options.
        /// </summary>
        public static string LoggedOffUserSectionLabel {
            get {
                return ResourceManager.GetString("LoggedOffUserSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0}.
        /// </summary>
        public static string LoggedOnUserSectionLabel {
            get {
                return ResourceManager.GetString("LoggedOnUserSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogoffUserLabel {
            get {
                return ResourceManager.GetString("LogoffUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogonUserLabel {
            get {
                return ResourceManager.GetString("LogonUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update theme details.
        /// </summary>
        public static string ThemeSectionLabel {
            get {
                return ResourceManager.GetString("ThemeSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update master page content.
        /// </summary>
        public static string UpdateMasterPageContentSectionLabel {
            get {
                return ResourceManager.GetString("UpdateMasterPageContentSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the form below to update this master page&apos;s details..
        /// </summary>
        public static string UpdateMasterPageDescription {
            get {
                return ResourceManager.GetString("UpdateMasterPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {1}.
        /// </summary>
        public static string UpdateMasterPageElementPageName {
            get {
                return ResourceManager.GetString("UpdateMasterPageElementPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0} master page.
        /// </summary>
        public static string UpdateMasterPageName {
            get {
                return ResourceManager.GetString("UpdateMasterPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name and details.
        /// </summary>
        public static string UpdateMasterPageOptionLabel {
            get {
                return ResourceManager.GetString("UpdateMasterPageOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update master page details.
        /// </summary>
        public static string UpdateMasterPageSectionLabel {
            get {
                return ResourceManager.GetString("UpdateMasterPageSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the form below to update the selected master page zone..
        /// </summary>
        public static string UpdateMasterPageZoneDescription {
            get {
                return ResourceManager.GetString("UpdateMasterPageZoneDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {1} zone of {0} master page.
        /// </summary>
        public static string UpdateMasterPageZoneName {
            get {
                return ResourceManager.GetString("UpdateMasterPageZoneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string UpdateMasterPageZoneOptionLabel {
            get {
                return ResourceManager.GetString("UpdateMasterPageZoneOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update zones of {0} master page.
        /// </summary>
        public static string UpdateMasterPageZonesName {
            get {
                return ResourceManager.GetString("UpdateMasterPageZonesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or remove zones.
        /// </summary>
        public static string UpdateMasterPageZonesOptionLabel {
            get {
                return ResourceManager.GetString("UpdateMasterPageZonesOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update master page zones.
        /// </summary>
        public static string UpdateMasterPageZonesSectionLabel {
            get {
                return ResourceManager.GetString("UpdateMasterPageZonesSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update page content.
        /// </summary>
        public static string UpdatePageContentSectionLabel {
            get {
                return ResourceManager.GetString("UpdatePageContentSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the form below to update this page&apos;s details..
        /// </summary>
        public static string UpdatePageDescription {
            get {
                return ResourceManager.GetString("UpdatePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {1}.
        /// </summary>
        public static string UpdatePageElementPageName {
            get {
                return ResourceManager.GetString("UpdatePageElementPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0}.
        /// </summary>
        public static string UpdatePageName {
            get {
                return ResourceManager.GetString("UpdatePageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name and details.
        /// </summary>
        public static string UpdatePageOptionLabel {
            get {
                return ResourceManager.GetString("UpdatePageOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update page details.
        /// </summary>
        public static string UpdatePageSectionLabel {
            get {
                return ResourceManager.GetString("UpdatePageSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the form below to add or remove content from this page..
        /// </summary>
        public static string UpdatePageZoneDescription {
            get {
                return ResourceManager.GetString("UpdatePageZoneDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string UpdatePageZoneOptionLabel {
            get {
                return ResourceManager.GetString("UpdatePageZoneOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update page zones.
        /// </summary>
        public static string UpdatePageZonesSectionLabel {
            get {
                return ResourceManager.GetString("UpdatePageZonesSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update your website&apos;s fonts and colours..
        /// </summary>
        public static string UpdateThemeDescription {
            get {
                return ResourceManager.GetString("UpdateThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update theme.
        /// </summary>
        public static string UpdateThemeName {
            get {
                return ResourceManager.GetString("UpdateThemeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update your profile.
        /// </summary>
        public static string UpdateUserLabel {
            get {
                return ResourceManager.GetString("UpdateUserLabel", resourceCulture);
            }
        }
    }
}
