//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Riverside.Cms.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AuthenticationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthenticationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Riverside.Cms.Core.Resources.AuthenticationResource", typeof(AuthenticationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AliasLabel {
            get {
                return ResourceManager.GetString("AliasLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be more than {1} characters..
        /// </summary>
        public static string AliasMaxLengthMessage {
            get {
                return ResourceManager.GetString("AliasMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name not available..
        /// </summary>
        public static string AliasNotAvailableMessage {
            get {
                return ResourceManager.GetString("AliasNotAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string AliasRequiredMessage {
            get {
                return ResourceManager.GetString("AliasRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePasswordButtonLabel {
            get {
                return ResourceManager.GetString("ChangePasswordButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ChangePasswordConfirmPasswordLabel {
            get {
                return ResourceManager.GetString("ChangePasswordConfirmPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation is required..
        /// </summary>
        public static string ChangePasswordConfirmPasswordRequiredMessage {
            get {
                return ResourceManager.GetString("ChangePasswordConfirmPasswordRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is invalid..
        /// </summary>
        public static string ChangePasswordCurrentPasswordInvalidMessage {
            get {
                return ResourceManager.GetString("ChangePasswordCurrentPasswordInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string ChangePasswordCurrentPasswordLabel {
            get {
                return ResourceManager.GetString("ChangePasswordCurrentPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is required..
        /// </summary>
        public static string ChangePasswordCurrentPasswordRequiredMessage {
            get {
                return ResourceManager.GetString("ChangePasswordCurrentPasswordRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many change password attempts. Your account has been temporarily locked out. Log in to this site later and try changing your password again. If you have forgotten your password, go to the user options menu and reset your password..
        /// </summary>
        public static string ChangePasswordLogonMessage {
            get {
                return ResourceManager.GetString("ChangePasswordLogonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string ChangePasswordNewPasswordLabel {
            get {
                return ResourceManager.GetString("ChangePasswordNewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password must be between {2} and {1} characters long..
        /// </summary>
        public static string ChangePasswordNewPasswordLengthMessage {
            get {
                return ResourceManager.GetString("ChangePasswordNewPasswordLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is required..
        /// </summary>
        public static string ChangePasswordNewPasswordRequiredMessage {
            get {
                return ResourceManager.GetString("ChangePasswordNewPasswordRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your current and new passwords to change your password..
        /// </summary>
        public static string ChangePasswordPageDescription {
            get {
                return ResourceManager.GetString("ChangePasswordPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        public static string ChangePasswordPageName {
            get {
                return ResourceManager.GetString("ChangePasswordPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new passwords supplied do not match..
        /// </summary>
        public static string ChangePasswordPasswordsDoNotMatchMessage {
            get {
                return ResourceManager.GetString("ChangePasswordPasswordsDoNotMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been updated..
        /// </summary>
        public static string ChangePasswordSuccessMessage {
            get {
                return ResourceManager.GetString("ChangePasswordSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user..
        /// </summary>
        public static string ChangePasswordUserDisabledMessage {
            get {
                return ResourceManager.GetString("ChangePasswordUserDisabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account locked out. Please try again later..
        /// </summary>
        public static string ChangePasswordUserLockedOutMessage {
            get {
                return ResourceManager.GetString("ChangePasswordUserLockedOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user..
        /// </summary>
        public static string ChangePasswordUserNotFoundMessage {
            get {
                return ResourceManager.GetString("ChangePasswordUserNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user..
        /// </summary>
        public static string ChangePasswordUserUnconfirmedMessage {
            get {
                return ResourceManager.GetString("ChangePasswordUserUnconfirmedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account activation failed..
        /// </summary>
        public static string ConfirmUserConfirmedMessage {
            get {
                return ResourceManager.GetString("ConfirmUserConfirmedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmUserConfirmPasswordLabel {
            get {
                return ResourceManager.GetString("ConfirmUserConfirmPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation is required..
        /// </summary>
        public static string ConfirmUserConfirmPasswordRequiredMessage {
            get {
                return ResourceManager.GetString("ConfirmUserConfirmPasswordRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account activation failed..
        /// </summary>
        public static string ConfirmUserDisabledMessage {
            get {
                return ResourceManager.GetString("ConfirmUserDisabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem activating your account. Please contact the site administrators..
        /// </summary>
        public static string ConfirmUserFailureMessage {
            get {
                return ResourceManager.GetString("ConfirmUserFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now that you have re-activated your account, you can log back in to this site..
        /// </summary>
        public static string ConfirmUserLogonMessage {
            get {
                return ResourceManager.GetString("ConfirmUserLogonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account activation failed..
        /// </summary>
        public static string ConfirmUserNotFoundMessage {
            get {
                return ResourceManager.GetString("ConfirmUserNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate account.
        /// </summary>
        public static string ConfirmUserPageName {
            get {
                return ResourceManager.GetString("ConfirmUserPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string ConfirmUserPasswordLabel {
            get {
                return ResourceManager.GetString("ConfirmUserPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be between {2} and {1} characters long..
        /// </summary>
        public static string ConfirmUserPasswordLengthMessage {
            get {
                return ResourceManager.GetString("ConfirmUserPasswordLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User confirmation failed..
        /// </summary>
        public static string ConfirmUserPasswordNotSetMessage {
            get {
                return ResourceManager.GetString("ConfirmUserPasswordNotSetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string ConfirmUserPasswordRequiredMessage {
            get {
                return ResourceManager.GetString("ConfirmUserPasswordRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords supplied do not match..
        /// </summary>
        public static string ConfirmUserPasswordsDoNotMatchMessage {
            get {
                return ResourceManager.GetString("ConfirmUserPasswordsDoNotMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account activation failed..
        /// </summary>
        public static string ConfirmUserPasswordSetMessage {
            get {
                return ResourceManager.GetString("ConfirmUserPasswordSetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate account and set password.
        /// </summary>
        public static string ConfirmUserSetPasswordButtonLabel {
            get {
                return ResourceManager.GetString("ConfirmUserSetPasswordButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem activating your account. Please contact the site administrators..
        /// </summary>
        public static string ConfirmUserSetPasswordFailureMessage {
            get {
                return ResourceManager.GetString("ConfirmUserSetPasswordFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now that you have activated your account, you can log in to this site..
        /// </summary>
        public static string ConfirmUserSetPasswordLogonMessage {
            get {
                return ResourceManager.GetString("ConfirmUserSetPasswordLogonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a password to complete the account activation process..
        /// </summary>
        public static string ConfirmUserSetPasswordPageDescription {
            get {
                return ResourceManager.GetString("ConfirmUserSetPasswordPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate account.
        /// </summary>
        public static string ConfirmUserSetPasswordPageName {
            get {
                return ResourceManager.GetString("ConfirmUserSetPasswordPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for activating your account. You can now log on to this site..
        /// </summary>
        public static string ConfirmUserSuccessMessage {
            get {
                return ResourceManager.GetString("ConfirmUserSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account activation request expired..
        /// </summary>
        public static string ConfirmUserTokenExpiredMessage {
            get {
                return ResourceManager.GetString("ConfirmUserTokenExpiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account activation failed..
        /// </summary>
        public static string ConfirmUserTokenInvalidMessage {
            get {
                return ResourceManager.GetString("ConfirmUserTokenInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string CreateUserButtonLabel {
            get {
                return ResourceManager.GetString("CreateUserButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;style&gt;
        ///h1 { margin: 20px 0 10px 0; padding: 0; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 36px; line-height: 1.1; color: #333333; }
        ///h2 { margin: 20px 0 10px 0; padding: 0; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 30px; line-height: 1.1; color: #333333; }
        ///p { margin: 10px 0 10px 0; padding: 0; width: 100%; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.4; color: #333333; }
        ///&lt;/style&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CreateUserEmailHtmlBody {
            get {
                return ResourceManager.GetString("CreateUserEmailHtmlBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registration
        ///
        ///Hello %ALIAS%
        ///
        ///An account has been created for you. Click the link below to set a password and activate your account.
        ///
        ///%CONFIRMURL%
        ///
        ///The link will expire at %CONFIRMEXPIRES%.
        ///
        ///Once you have clicked on the link and set your password, you will be able to login with your email address (%EMAIL%) and new password.
        ///
        ///Thanks!.
        /// </summary>
        public static string CreateUserEmailPlainTextBody {
            get {
                return ResourceManager.GetString("CreateUserEmailPlainTextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello %ALIAS% and welcome!.
        /// </summary>
        public static string CreateUserEmailSubject {
            get {
                return ResourceManager.GetString("CreateUserEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration is quick and easy. Fill out the form below to begin the process. Once you have created an account, you will receive an email containing instructions for activating your account. Once you have activated your account, you will be able to log on to this website..
        /// </summary>
        public static string CreateUserPageDescription {
            get {
                return ResourceManager.GetString("CreateUserPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string CreateUserPageName {
            get {
                return ResourceManager.GetString("CreateUserPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for creating an account. You will shortly receive an email containing instructions for activating your account. Once you have activated your account, you will be able to log on to this site..
        /// </summary>
        public static string CreateUserSuccessMessage {
            get {
                return ResourceManager.GetString("CreateUserSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is invalid..
        /// </summary>
        public static string EmailInvalidMessage {
            get {
                return ResourceManager.GetString("EmailInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address cannot be more than {1} characters..
        /// </summary>
        public static string EmailMaxLengthMessage {
            get {
                return ResourceManager.GetString("EmailMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not available..
        /// </summary>
        public static string EmailNotAvailableMessage {
            get {
                return ResourceManager.GetString("EmailNotAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is required..
        /// </summary>
        public static string EmailRequiredMessage {
            get {
                return ResourceManager.GetString("EmailRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten password.
        /// </summary>
        public static string ForgottenPasswordButtonLabel {
            get {
                return ResourceManager.GetString("ForgottenPasswordButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for submitting your email address. You will shortly receive an email containing instructions for resetting your password..
        /// </summary>
        public static string ForgottenPasswordCompletedMessage {
            get {
                return ResourceManager.GetString("ForgottenPasswordCompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;style&gt;
        ///h1 { margin: 20px 0 10px 0; padding: 0; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 36px; line-height: 1.1; color: #333333; }
        ///h2 { margin: 20px 0 10px 0; padding: 0; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 30px; line-height: 1.1; color: #333333; }
        ///p { margin: 10px 0 10px 0; padding: 0; width: 100%; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.4; color: #333333; }
        ///&lt;/style&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ForgottenPasswordEmailHtmlBody {
            get {
                return ResourceManager.GetString("ForgottenPasswordEmailHtmlBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is invalid..
        /// </summary>
        public static string ForgottenPasswordEmailInvalidMessage {
            get {
                return ResourceManager.GetString("ForgottenPasswordEmailInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ForgottenPasswordEmailLabel {
            get {
                return ResourceManager.GetString("ForgottenPasswordEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address cannot be more than {1} characters..
        /// </summary>
        public static string ForgottenPasswordEmailMaxLengthMessage {
            get {
                return ResourceManager.GetString("ForgottenPasswordEmailMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten password
        ///
        ///Hello %ALIAS%
        ///
        ///Click the link below to reset your password.
        ///
        ///%RESETPASSWORDURL%
        ///
        ///The link will expire at %RESETPASSWORDEXPIRES%.
        ///
        ///Once you have clicked on the link and set your password, you will be able to login with your email address (%EMAIL%) and new password.
        ///
        ///Thanks!.
        /// </summary>
        public static string ForgottenPasswordEmailPlainTextBody {
            get {
                return ResourceManager.GetString("ForgottenPasswordEmailPlainTextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is required..
        /// </summary>
        public static string ForgottenPasswordEmailRequiredMessage {
            get {
                return ResourceManager.GetString("ForgottenPasswordEmailRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password request.
        /// </summary>
        public static string ForgottenPasswordEmailSubject {
            get {
                return ResourceManager.GetString("ForgottenPasswordEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address to begin the password reset process. Once you have submitted your email address, you will receive an email containing instructions for resetting your password..
        /// </summary>
        public static string ForgottenPasswordPageDescription {
            get {
                return ResourceManager.GetString("ForgottenPasswordPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten password.
        /// </summary>
        public static string ForgottenPasswordPageName {
            get {
                return ResourceManager.GetString("ForgottenPasswordPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is invalid..
        /// </summary>
        public static string ForgottenPasswordUserDisabledMessage {
            get {
                return ResourceManager.GetString("ForgottenPasswordUserDisabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten password failed..
        /// </summary>
        public static string ForgottenPasswordUserNotConfirmedMessage {
            get {
                return ResourceManager.GetString("ForgottenPasswordUserNotConfirmedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is invalid..
        /// </summary>
        public static string ForgottenPasswordUserNotFoundMessage {
            get {
                return ResourceManager.GetString("ForgottenPasswordUserNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogonUserButtonLabel {
            get {
                return ResourceManager.GetString("LogonUserButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account? Register here..
        /// </summary>
        public static string LogonUserCreateUserLabel {
            get {
                return ResourceManager.GetString("LogonUserCreateUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address or password is invalid..
        /// </summary>
        public static string LogonUserCredentialsInvalidMessage {
            get {
                return ResourceManager.GetString("LogonUserCredentialsInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address or password is invalid..
        /// </summary>
        public static string LogonUserDisabledMessage {
            get {
                return ResourceManager.GetString("LogonUserDisabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten your password?.
        /// </summary>
        public static string LogonUserForgottenPasswordLabel {
            get {
                return ResourceManager.GetString("LogonUserForgottenPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account locked out. Please try again later..
        /// </summary>
        public static string LogonUserLockedOutMessage {
            get {
                return ResourceManager.GetString("LogonUserLockedOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to {0}..
        /// </summary>
        public static string LogonUserPageDescription {
            get {
                return ResourceManager.GetString("LogonUserPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogonUserPageName {
            get {
                return ResourceManager.GetString("LogonUserPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address or password is invalid..
        /// </summary>
        public static string LogonUserUnconfirmedMessage {
            get {
                return ResourceManager.GetString("LogonUserUnconfirmedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string PasswordRequiredMessage {
            get {
                return ResourceManager.GetString("PasswordRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMeLabel {
            get {
                return ResourceManager.GetString("RememberMeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ResetPasswordButtonLabel {
            get {
                return ResourceManager.GetString("ResetPasswordButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ResetPasswordConfirmPasswordLabel {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation is required..
        /// </summary>
        public static string ResetPasswordConfirmPasswordRequiredMessage {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmPasswordRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem resetting your password. Please contact the site administrators..
        /// </summary>
        public static string ResetPasswordFailureMessage {
            get {
                return ResourceManager.GetString("ResetPasswordFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset. You can now log in to this site with your new credentials..
        /// </summary>
        public static string ResetPasswordLogonMessage {
            get {
                return ResourceManager.GetString("ResetPasswordLogonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a password to complete the forgotten password reset process..
        /// </summary>
        public static string ResetPasswordPageDescription {
            get {
                return ResourceManager.GetString("ResetPasswordPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ResetPasswordPageName {
            get {
                return ResourceManager.GetString("ResetPasswordPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string ResetPasswordPasswordLabel {
            get {
                return ResourceManager.GetString("ResetPasswordPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be between {2} and {1} characters long..
        /// </summary>
        public static string ResetPasswordPasswordLengthMessage {
            get {
                return ResourceManager.GetString("ResetPasswordPasswordLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string ResetPasswordPasswordRequiredMessage {
            get {
                return ResourceManager.GetString("ResetPasswordPasswordRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords supplied do not match..
        /// </summary>
        public static string ResetPasswordPasswordsDoNotMatchMessage {
            get {
                return ResourceManager.GetString("ResetPasswordPasswordsDoNotMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password request expired..
        /// </summary>
        public static string ResetPasswordTokenExpiredMessage {
            get {
                return ResourceManager.GetString("ResetPasswordTokenExpiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password failed..
        /// </summary>
        public static string ResetPasswordTokenInvalidMessage {
            get {
                return ResourceManager.GetString("ResetPasswordTokenInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password failed..
        /// </summary>
        public static string ResetPasswordUserDisabledMessage {
            get {
                return ResourceManager.GetString("ResetPasswordUserDisabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password failed..
        /// </summary>
        public static string ResetPasswordUserNotFoundMessage {
            get {
                return ResourceManager.GetString("ResetPasswordUserNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string UpdateUserAliasLabel {
            get {
                return ResourceManager.GetString("UpdateUserAliasLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be more than {1} characters..
        /// </summary>
        public static string UpdateUserAliasMaxLengthMessage {
            get {
                return ResourceManager.GetString("UpdateUserAliasMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name not available..
        /// </summary>
        public static string UpdateUserAliasNotAvailableMessage {
            get {
                return ResourceManager.GetString("UpdateUserAliasNotAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string UpdateUserAliasRequiredMessage {
            get {
                return ResourceManager.GetString("UpdateUserAliasRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update profile.
        /// </summary>
        public static string UpdateUserButtonLabel {
            get {
                return ResourceManager.GetString("UpdateUserButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;style&gt;
        ///h1 { margin: 20px 0 10px 0; padding: 0; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 36px; line-height: 1.1; color: #333333; }
        ///h2 { margin: 20px 0 10px 0; padding: 0; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 30px; line-height: 1.1; color: #333333; }
        ///p { margin: 10px 0 10px 0; padding: 0; width: 100%; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.4; color: #333333; }
        ///&lt;/style&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string UpdateUserEmailHtmlBody {
            get {
                return ResourceManager.GetString("UpdateUserEmailHtmlBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is invalid..
        /// </summary>
        public static string UpdateUserEmailInvalidMessage {
            get {
                return ResourceManager.GetString("UpdateUserEmailInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string UpdateUserEmailLabel {
            get {
                return ResourceManager.GetString("UpdateUserEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address cannot be more than {1} characters..
        /// </summary>
        public static string UpdateUserEmailMaxLengthMessage {
            get {
                return ResourceManager.GetString("UpdateUserEmailMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not available..
        /// </summary>
        public static string UpdateUserEmailNotAvailableMessage {
            get {
                return ResourceManager.GetString("UpdateUserEmailNotAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account updated
        ///
        ///Hello %ALIAS%
        ///
        ///Your account has been updated. Click the link below to re-activate your account.
        ///
        ///%CONFIRMURL%
        ///
        ///The link will expire at %CONFIRMEXPIRES%.
        ///
        ///Once you have clicked on the link and re-activated your account, you will be able to login with your new email address (%EMAIL%) and password.
        ///
        ///Thanks!.
        /// </summary>
        public static string UpdateUserEmailPlainTextBody {
            get {
                return ResourceManager.GetString("UpdateUserEmailPlainTextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is required..
        /// </summary>
        public static string UpdateUserEmailRequiredMessage {
            get {
                return ResourceManager.GetString("UpdateUserEmailRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello %ALIAS%, your account has been updated.
        /// </summary>
        public static string UpdateUserEmailSubject {
            get {
                return ResourceManager.GetString("UpdateUserEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar must be at least {0} by {1} pixels in size..
        /// </summary>
        public static string UpdateUserImageDimensionsInvalidMessage {
            get {
                return ResourceManager.GetString("UpdateUserImageDimensionsInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar does not appear to be a valid image..
        /// </summary>
        public static string UpdateUserImageInvalidMessage {
            get {
                return ResourceManager.GetString("UpdateUserImageInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed an avatar..
        /// </summary>
        public static string UpdateUserImageNotAllowedMessage {
            get {
                return ResourceManager.GetString("UpdateUserImageNotAllowedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As your email address has changed, you will need to re-activate your account. You will shortly receive an email containing instructions for activating your account. Once you have activated your account, you will be able to log back in to this site..
        /// </summary>
        public static string UpdateUserLogonMessage {
            get {
                return ResourceManager.GetString("UpdateUserLogonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you change your email address, you will need to re-activate your account. If you change your email address, you will receive an email containing instructions for re-activating your account. Once you have re-activated your account, you will be able to log back in to this website..
        /// </summary>
        public static string UpdateUserPageDescription {
            get {
                return ResourceManager.GetString("UpdateUserPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update your profile.
        /// </summary>
        public static string UpdateUserPageName {
            get {
                return ResourceManager.GetString("UpdateUserPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your details have been updated..
        /// </summary>
        public static string UpdateUserSuccessMessage {
            get {
                return ResourceManager.GetString("UpdateUserSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        public static string UpdateUserUploadLabel {
            get {
                return ResourceManager.GetString("UpdateUserUploadLabel", resourceCulture);
            }
        }
    }
}
