//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Riverside.Cms.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DomainResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DomainResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Riverside.Cms.Core.Resources.DomainResource", typeof(DomainResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Domain.
        /// </summary>
        public static string CreateDomainButtonLabel {
            get {
                return ResourceManager.GetString("CreateDomainButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateDomainTabLabel {
            get {
                return ResourceManager.GetString("CreateDomainTabLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Domain.
        /// </summary>
        public static string DeleteDomainButtonLabel {
            get {
                return ResourceManager.GetString("DeleteDomainButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteDomainTabLabel {
            get {
                return ResourceManager.GetString("DeleteDomainTabLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No domains found.
        /// </summary>
        public static string NoDomainsMessage {
            get {
                return ResourceManager.GetString("NoDomainsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string ReadDomainTabLabel {
            get {
                return ResourceManager.GetString("ReadDomainTabLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect URL is invalid.
        /// </summary>
        public static string RedirectUrlInvalidMessage {
            get {
                return ResourceManager.GetString("RedirectUrlInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect URL.
        /// </summary>
        public static string RedirectUrlLabel {
            get {
                return ResourceManager.GetString("RedirectUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect URL cannot be more than {1} characters long.
        /// </summary>
        public static string RedirectUrlMaxLengthMessage {
            get {
                return ResourceManager.GetString("RedirectUrlMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Domain.
        /// </summary>
        public static string UpdateDomainButtonLabel {
            get {
                return ResourceManager.GetString("UpdateDomainButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateDomainTabLabel {
            get {
                return ResourceManager.GetString("UpdateDomainTabLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL is invalid.
        /// </summary>
        public static string UrlInvalidMessage {
            get {
                return ResourceManager.GetString("UrlInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniform resource locator.
        /// </summary>
        public static string UrlLabel {
            get {
                return ResourceManager.GetString("UrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL cannot be more than {1} characters long.
        /// </summary>
        public static string UrlMaxLengthMessage {
            get {
                return ResourceManager.GetString("UrlMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL chosen is not available.
        /// </summary>
        public static string UrlNotAvailableMessage {
            get {
                return ResourceManager.GetString("UrlNotAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL is required.
        /// </summary>
        public static string UrlRequiredMessage {
            get {
                return ResourceManager.GetString("UrlRequiredMessage", resourceCulture);
            }
        }
    }
}
