//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Riverside.Cms.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MasterPageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MasterPageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Riverside.Cms.Core.Resources.MasterPageResource", typeof(MasterPageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this master page for administering the CMS?.
        /// </summary>
        public static string AdministrationLabel {
            get {
                return ResourceManager.GetString("AdministrationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone type.
        /// </summary>
        public static string AdminTypeLabel {
            get {
                return ResourceManager.GetString("AdminTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone type is required..
        /// </summary>
        public static string AdminTypeRequiredMessage {
            get {
                return ResourceManager.GetString("AdminTypeRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select parent folder (if required).
        /// </summary>
        public static string AncestorPageIdDefaultOption {
            get {
                return ResourceManager.GetString("AncestorPageIdDefaultOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent folder of pages.
        /// </summary>
        public static string AncestorPageIdLabel {
            get {
                return ResourceManager.GetString("AncestorPageIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select relation.
        /// </summary>
        public static string AncestorPageLevelDefaultOption {
            get {
                return ResourceManager.GetString("AncestorPageLevelDefaultOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation of parent folder to pages.
        /// </summary>
        public static string AncestorPageLevelLabel {
            get {
                return ResourceManager.GetString("AncestorPageLevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation of parent folder to pages is required..
        /// </summary>
        public static string AncestorPageLevelRequiredMessage {
            get {
                return ResourceManager.GetString("AncestorPageLevelRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML at beginning of page.
        /// </summary>
        public static string BeginRenderLabel {
            get {
                return ResourceManager.GetString("BeginRenderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelZoneButtonLabel {
            get {
                return ResourceManager.GetString("CancelZoneButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelZoneElementButtonLabel {
            get {
                return ResourceManager.GetString("CancelZoneElementButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelZoneElementNewButtonLabel {
            get {
                return ResourceManager.GetString("CancelZoneElementNewButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelZoneElementTypeButtonLabel {
            get {
                return ResourceManager.GetString("CancelZoneElementTypeButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone content.
        /// </summary>
        public static string ContentTypeLabel {
            get {
                return ResourceManager.GetString("ContentTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone content is required..
        /// </summary>
        public static string ContentTypeRequiredMessage {
            get {
                return ResourceManager.GetString("ContentTypeRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can pages be created?.
        /// </summary>
        public static string CreatableLabel {
            get {
                return ResourceManager.GetString("CreatableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Master Page.
        /// </summary>
        public static string CreateMasterPageActionLabel {
            get {
                return ResourceManager.GetString("CreateMasterPageActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create master page.
        /// </summary>
        public static string CreateMasterPageButtonLabel {
            get {
                return ResourceManager.GetString("CreateMasterPageButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new zone.
        /// </summary>
        public static string CreateZoneButtonLabel {
            get {
                return ResourceManager.GetString("CreateZoneButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add existing element.
        /// </summary>
        public static string CreateZoneElementButtonLabel {
            get {
                return ResourceManager.GetString("CreateZoneElementButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new element.
        /// </summary>
        public static string CreateZoneElementNewButtonLabel {
            get {
                return ResourceManager.GetString("CreateZoneElementNewButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add allowed element type to zone.
        /// </summary>
        public static string CreateZoneElementTypeButtonLabel {
            get {
                return ResourceManager.GetString("CreateZoneElementTypeButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can pages be deleted?.
        /// </summary>
        public static string DeletableLabel {
            get {
                return ResourceManager.GetString("DeletableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}.
        /// </summary>
        public static string DeleteMasterPageActionLabel {
            get {
                return ResourceManager.GetString("DeleteMasterPageActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select element.
        /// </summary>
        public static string ElementIdDefaultOption {
            get {
                return ResourceManager.GetString("ElementIdDefaultOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element.
        /// </summary>
        public static string ElementIdLabel {
            get {
                return ResourceManager.GetString("ElementIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element is required..
        /// </summary>
        public static string ElementIdRequiredMessage {
            get {
                return ResourceManager.GetString("ElementIdRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New element information is invalid..
        /// </summary>
        public static string ElementInvalidMessage {
            get {
                return ResourceManager.GetString("ElementInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element name is invalid. It must not contain a forward slash..
        /// </summary>
        public static string ElementNameInvalidMessage {
            get {
                return ResourceManager.GetString("ElementNameInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element name.
        /// </summary>
        public static string ElementNameLabel {
            get {
                return ResourceManager.GetString("ElementNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element name cannot be more than {1} characters long..
        /// </summary>
        public static string ElementNameMaxLengthMessage {
            get {
                return ResourceManager.GetString("ElementNameMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element name is required..
        /// </summary>
        public static string ElementNameRequiredMessage {
            get {
                return ResourceManager.GetString("ElementNameRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select element type.
        /// </summary>
        public static string ElementTypeIdDefaultOption {
            get {
                return ResourceManager.GetString("ElementTypeIdDefaultOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element type.
        /// </summary>
        public static string ElementTypeIdLabel {
            get {
                return ResourceManager.GetString("ElementTypeIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element type is required..
        /// </summary>
        public static string ElementTypeIdRequiredMessage {
            get {
                return ResourceManager.GetString("ElementTypeIdRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element type.
        /// </summary>
        public static string ElementTypeLabel {
            get {
                return ResourceManager.GetString("ElementTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element type is required..
        /// </summary>
        public static string ElementTypeRequiredMessage {
            get {
                return ResourceManager.GetString("ElementTypeRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML at end of page.
        /// </summary>
        public static string EndRenderLabel {
            get {
                return ResourceManager.GetString("EndRenderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do pages have an image?.
        /// </summary>
        public static string HasImageLabel {
            get {
                return ResourceManager.GetString("HasImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do pages have an occurred date?.
        /// </summary>
        public static string HasOccurredLabel {
            get {
                return ResourceManager.GetString("HasOccurredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum height of original image.
        /// </summary>
        public static string ImageMinHeightLabel {
            get {
                return ResourceManager.GetString("ImageMinHeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum height of original image must not be larger than {1} pixels..
        /// </summary>
        public static string ImageMinHeightMaxErrorMessage {
            get {
                return ResourceManager.GetString("ImageMinHeightMaxErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum height of original image must be at least {1} pixels..
        /// </summary>
        public static string ImageMinHeightMinErrorMessage {
            get {
                return ResourceManager.GetString("ImageMinHeightMinErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum height of original image is required..
        /// </summary>
        public static string ImageMinHeightRequiredMessage {
            get {
                return ResourceManager.GetString("ImageMinHeightRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum width of original image.
        /// </summary>
        public static string ImageMinWidthLabel {
            get {
                return ResourceManager.GetString("ImageMinWidthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum width of original image must not be larger than {1} pixels..
        /// </summary>
        public static string ImageMinWidthMaxErrorMessage {
            get {
                return ResourceManager.GetString("ImageMinWidthMaxErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum width of original image must be at least {1} pixels..
        /// </summary>
        public static string ImageMinWidthMinErrorMessage {
            get {
                return ResourceManager.GetString("ImageMinWidthMinErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum width of original image is required..
        /// </summary>
        public static string ImageMinWidthRequiredMessage {
            get {
                return ResourceManager.GetString("ImageMinWidthRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag to reorder.
        /// </summary>
        public static string MasterPageZoneDragLabel {
            get {
                return ResourceManager.GetString("MasterPageZoneDragLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag to reorder.
        /// </summary>
        public static string MasterPageZoneElementDragLabel {
            get {
                return ResourceManager.GetString("MasterPageZoneElementDragLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout name must not start or end with white space.
        /// </summary>
        public static string NameInvalidMessage {
            get {
                return ResourceManager.GetString("NameInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master page name.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master page name cannot be more than {1} characters long.
        /// </summary>
        public static string NameMaxLengthMessage {
            get {
                return ResourceManager.GetString("NameMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master page name is required..
        /// </summary>
        public static string NameRequiredMessage {
            get {
                return ResourceManager.GetString("NameRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No master pages found.
        /// </summary>
        public static string NoMasterPagesMessage {
            get {
                return ResourceManager.GetString("NoMasterPagesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial description given to pages.
        /// </summary>
        public static string PageDescriptionLabel {
            get {
                return ResourceManager.GetString("PageDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial name given to pages.
        /// </summary>
        public static string PageNameLabel {
            get {
                return ResourceManager.GetString("PageNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial name given to pages cannot be more than {1} characters long..
        /// </summary>
        public static string PageNameMaxLengthMessage {
            get {
                return ResourceManager.GetString("PageNameMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial name given to pages is required..
        /// </summary>
        public static string PageNameRequiredMessage {
            get {
                return ResourceManager.GetString("PageNameRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of pages.
        /// </summary>
        public static string PageTypeLabel {
            get {
                return ResourceManager.GetString("PageTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of pages is required..
        /// </summary>
        public static string PageTypeRequiredMessage {
            get {
                return ResourceManager.GetString("PageTypeRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview image height.
        /// </summary>
        public static string PreviewImageHeightLabel {
            get {
                return ResourceManager.GetString("PreviewImageHeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview image height must not be larger than {1} pixels..
        /// </summary>
        public static string PreviewImageHeightMaxErrorMessage {
            get {
                return ResourceManager.GetString("PreviewImageHeightMaxErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview image height must be at least {1} pixels..
        /// </summary>
        public static string PreviewImageHeightMinErrorMessage {
            get {
                return ResourceManager.GetString("PreviewImageHeightMinErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview image height is required..
        /// </summary>
        public static string PreviewImageHeightRequiredMessage {
            get {
                return ResourceManager.GetString("PreviewImageHeightRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview image resize mode.
        /// </summary>
        public static string PreviewImageResizeModeLabel {
            get {
                return ResourceManager.GetString("PreviewImageResizeModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview image resize mode is required..
        /// </summary>
        public static string PreviewImageResizeModeRequiredMessage {
            get {
                return ResourceManager.GetString("PreviewImageResizeModeRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview image width.
        /// </summary>
        public static string PreviewImageWidthLabel {
            get {
                return ResourceManager.GetString("PreviewImageWidthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview image width must not be larger than {1} pixels..
        /// </summary>
        public static string PreviewImageWidthMaxErrorMessage {
            get {
                return ResourceManager.GetString("PreviewImageWidthMaxErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview image width must be at least {1} pixels..
        /// </summary>
        public static string PreviewImageWidthMinErrorMessage {
            get {
                return ResourceManager.GetString("PreviewImageWidthMinErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview image width is required..
        /// </summary>
        public static string PreviewImageWidthRequiredMessage {
            get {
                return ResourceManager.GetString("PreviewImageWidthRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View {0}.
        /// </summary>
        public static string ReadMasterPageActionLabel {
            get {
                return ResourceManager.GetString("ReadMasterPageActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string ReadMasterPageBreadcrumbLabel {
            get {
                return ResourceManager.GetString("ReadMasterPageBreadcrumbLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select resize mode.
        /// </summary>
        public static string ResizeModeDefaultOption {
            get {
                return ResourceManager.GetString("ResizeModeDefaultOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Pages.
        /// </summary>
        public static string SearchMasterPagesBreadcrumbLabel {
            get {
                return ResourceManager.GetString("SearchMasterPagesBreadcrumbLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can pages be tagged?.
        /// </summary>
        public static string TaggableLabel {
            get {
                return ResourceManager.GetString("TaggableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail image height.
        /// </summary>
        public static string ThumbnailImageHeightLabel {
            get {
                return ResourceManager.GetString("ThumbnailImageHeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail image height must not be larger than {1} pixels..
        /// </summary>
        public static string ThumbnailImageHeightMaxErrorMessage {
            get {
                return ResourceManager.GetString("ThumbnailImageHeightMaxErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail image height must be at least {1} pixels..
        /// </summary>
        public static string ThumbnailImageHeightMinErrorMessage {
            get {
                return ResourceManager.GetString("ThumbnailImageHeightMinErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail image height is required..
        /// </summary>
        public static string ThumbnailImageHeightRequiredMessage {
            get {
                return ResourceManager.GetString("ThumbnailImageHeightRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail image resize mode.
        /// </summary>
        public static string ThumbnailImageResizeModeLabel {
            get {
                return ResourceManager.GetString("ThumbnailImageResizeModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail image resize mode is required..
        /// </summary>
        public static string ThumbnailImageResizeModeRequiredMessage {
            get {
                return ResourceManager.GetString("ThumbnailImageResizeModeRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail image width.
        /// </summary>
        public static string ThumbnailImageWidthLabel {
            get {
                return ResourceManager.GetString("ThumbnailImageWidthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail image width must not be larger than {1} pixels..
        /// </summary>
        public static string ThumbnailImageWidthMaxErrorMessage {
            get {
                return ResourceManager.GetString("ThumbnailImageWidthMaxErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail image width must be at least {1} pixels..
        /// </summary>
        public static string ThumbnailImageWidthMinErrorMessage {
            get {
                return ResourceManager.GetString("ThumbnailImageWidthMinErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail image width is required..
        /// </summary>
        public static string ThumbnailImageWidthRequiredMessage {
            get {
                return ResourceManager.GetString("ThumbnailImageWidthRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0}.
        /// </summary>
        public static string UpdateMasterPageActionLabel {
            get {
                return ResourceManager.GetString("UpdateMasterPageActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update master page.
        /// </summary>
        public static string UpdateMasterPageButtonLabel {
            get {
                return ResourceManager.GetString("UpdateMasterPageButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update zone.
        /// </summary>
        public static string UpdateZoneButtonLabel {
            get {
                return ResourceManager.GetString("UpdateZoneButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update zone element.
        /// </summary>
        public static string UpdateZoneElementButtonLabel {
            get {
                return ResourceManager.GetString("UpdateZoneElementButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update zone element.
        /// </summary>
        public static string UpdateZoneElementNewButtonLabel {
            get {
                return ResourceManager.GetString("UpdateZoneElementNewButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update zone element type.
        /// </summary>
        public static string UpdateZoneElementTypeButtonLabel {
            get {
                return ResourceManager.GetString("UpdateZoneElementTypeButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update zones.
        /// </summary>
        public static string UpdateZonesButtonLabel {
            get {
                return ResourceManager.GetString("UpdateZonesButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurable.
        /// </summary>
        public static string ZoneAdminTypeConfigurableLabel {
            get {
                return ResourceManager.GetString("ZoneAdminTypeConfigurableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editable content.
        /// </summary>
        public static string ZoneAdminTypeEditableLabel {
            get {
                return ResourceManager.GetString("ZoneAdminTypeEditableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed content.
        /// </summary>
        public static string ZoneAdminTypeStaticLabel {
            get {
                return ResourceManager.GetString("ZoneAdminTypeStaticLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML before zone.
        /// </summary>
        public static string ZoneBeginRenderLabel {
            get {
                return ResourceManager.GetString("ZoneBeginRenderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string ZoneContentTypeCommentLabel {
            get {
                return ResourceManager.GetString("ZoneContentTypeCommentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string ZoneContentTypeMainLabel {
            get {
                return ResourceManager.GetString("ZoneContentTypeMainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string ZoneContentTypeStandardLabel {
            get {
                return ResourceManager.GetString("ZoneContentTypeStandardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML before element.
        /// </summary>
        public static string ZoneElementBeginRenderLabel {
            get {
                return ResourceManager.GetString("ZoneElementBeginRenderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML after element.
        /// </summary>
        public static string ZoneElementEndRenderLabel {
            get {
                return ResourceManager.GetString("ZoneElementEndRenderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML after zone.
        /// </summary>
        public static string ZoneEndRenderLabel {
            get {
                return ResourceManager.GetString("ZoneEndRenderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone name.
        /// </summary>
        public static string ZoneNameLabel {
            get {
                return ResourceManager.GetString("ZoneNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone name cannot be more than {1} characters long..
        /// </summary>
        public static string ZoneNameMaxLengthMessage {
            get {
                return ResourceManager.GetString("ZoneNameMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone name is required..
        /// </summary>
        public static string ZoneNameRequiredMessage {
            get {
                return ResourceManager.GetString("ZoneNameRequiredMessage", resourceCulture);
            }
        }
    }
}
