//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Riverside.Cms.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Riverside.Cms.Core.Resources.PageResource", typeof(PageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string CreatedLabel {
            get {
                return ResourceManager.GetString("CreatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create {0}.
        /// </summary>
        public static string CreatePageButtonLabel {
            get {
                return ResourceManager.GetString("CreatePageButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image must be at least {0} by {1} pixels in size..
        /// </summary>
        public static string ImageDimensionsInvalidMessage {
            get {
                return ResourceManager.GetString("ImageDimensionsInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload does not appear to be a valid image..
        /// </summary>
        public static string ImageInvalidMessage {
            get {
                return ResourceManager.GetString("ImageInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to set an image for this page..
        /// </summary>
        public static string ImageNotAllowedMessage {
            get {
                return ResourceManager.GetString("ImageNotAllowedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must not start or end with white space.
        /// </summary>
        public static string NameInvalidMessage {
            get {
                return ResourceManager.GetString("NameInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be more than {1} characters long.
        /// </summary>
        public static string NameMaxLengthMessage {
            get {
                return ResourceManager.GetString("NameMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string NameRequiredMessage {
            get {
                return ResourceManager.GetString("NameRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pages found.
        /// </summary>
        public static string NoPagesMessage {
            get {
                return ResourceManager.GetString("NoPagesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurred.
        /// </summary>
        public static string OccurredLabel {
            get {
                return ResourceManager.GetString("OccurredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grandparent.
        /// </summary>
        public static string PageLevelGrandparentLabel {
            get {
                return ResourceManager.GetString("PageLevelGrandparentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great Grandparent.
        /// </summary>
        public static string PageLevelGreatGrandparentLabel {
            get {
                return ResourceManager.GetString("PageLevelGreatGrandparentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        public static string PageLevelParentLabel {
            get {
                return ResourceManager.GetString("PageLevelParentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string PageTypeDocumentLabel {
            get {
                return ResourceManager.GetString("PageTypeDocumentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string PageTypeFolderLabel {
            get {
                return ResourceManager.GetString("PageTypeFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add content.
        /// </summary>
        public static string PageZoneAddElementButtonLabel {
            get {
                return ResourceManager.GetString("PageZoneAddElementButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update content.
        /// </summary>
        public static string PageZoneAdminButtonLabel {
            get {
                return ResourceManager.GetString("PageZoneAdminButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove content.
        /// </summary>
        public static string PageZoneDeleteElementButtonLabel {
            get {
                return ResourceManager.GetString("PageZoneDeleteElementButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML before element.
        /// </summary>
        public static string PageZoneElementBeginRenderLabel {
            get {
                return ResourceManager.GetString("PageZoneElementBeginRenderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML after element.
        /// </summary>
        public static string PageZoneElementEndRenderLabel {
            get {
                return ResourceManager.GetString("PageZoneElementEndRenderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate existing content..
        /// </summary>
        public static string PageZoneElementInvalidMessage {
            get {
                return ResourceManager.GetString("PageZoneElementInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PageZoneElementNameLabel {
            get {
                return ResourceManager.GetString("PageZoneElementNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content name cannot be more than {1} characters long..
        /// </summary>
        public static string PageZoneElementNameMaxLengthMessage {
            get {
                return ResourceManager.GetString("PageZoneElementNameMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content name is required..
        /// </summary>
        public static string PageZoneElementNameRequiredMessage {
            get {
                return ResourceManager.GetString("PageZoneElementNameRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of content to add.
        /// </summary>
        public static string PageZoneElementSelectLabel {
            get {
                return ResourceManager.GetString("PageZoneElementSelectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one piece of content is required..
        /// </summary>
        public static string PageZoneElementsRequiredMessage {
            get {
                return ResourceManager.GetString("PageZoneElementsRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of content.
        /// </summary>
        public static string PageZoneElementTypeLabel {
            get {
                return ResourceManager.GetString("PageZoneElementTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of content is required..
        /// </summary>
        public static string PageZoneElementTypeRequiredMessage {
            get {
                return ResourceManager.GetString("PageZoneElementTypeRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update content..
        /// </summary>
        public static string PageZoneInvalidMessage {
            get {
                return ResourceManager.GetString("PageZoneInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent folder is invalid.
        /// </summary>
        public static string ParentInvalidMessage {
            get {
                return ResourceManager.GetString("ParentInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent folder.
        /// </summary>
        public static string ParentLabel {
            get {
                return ResourceManager.GetString("ParentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent folder is required.
        /// </summary>
        public static string ParentRequiredMessage {
            get {
                return ResourceManager.GetString("ParentRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string SearchPagesBreadcrumbLabel {
            get {
                return ResourceManager.GetString("SearchPagesBreadcrumbLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select parent folder.
        /// </summary>
        public static string SelectParentLabel {
            get {
                return ResourceManager.GetString("SelectParentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags (one per line).
        /// </summary>
        public static string TagsLabel {
            get {
                return ResourceManager.GetString("TagsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated.
        /// </summary>
        public static string UpdatedLabel {
            get {
                return ResourceManager.GetString("UpdatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update page.
        /// </summary>
        public static string UpdatePageButtonLabel {
            get {
                return ResourceManager.GetString("UpdatePageButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string UploadLabel {
            get {
                return ResourceManager.GetString("UploadLabel", resourceCulture);
            }
        }
    }
}
