//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Riverside.Cms.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Riverside.Cms.Core.Resources.WebResource", typeof(WebResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Website.
        /// </summary>
        public static string CreateWebActionLabel {
            get {
                return ResourceManager.GetString("CreateWebActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Website.
        /// </summary>
        public static string CreateWebBreadcrumbLabel {
            get {
                return ResourceManager.GetString("CreateWebBreadcrumbLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Website.
        /// </summary>
        public static string CreateWebButtonLabel {
            get {
                return ResourceManager.GetString("CreateWebButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateWebTabLabel {
            get {
                return ResourceManager.GetString("CreateWebTabLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}.
        /// </summary>
        public static string DeleteWebActionLabel {
            get {
                return ResourceManager.GetString("DeleteWebActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Website.
        /// </summary>
        public static string DeleteWebButtonLabel {
            get {
                return ResourceManager.GetString("DeleteWebButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteWebTabLabel {
            get {
                return ResourceManager.GetString("DeleteWebTabLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website name must not start or end with white space.
        /// </summary>
        public static string NameInvalidMessage {
            get {
                return ResourceManager.GetString("NameInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website name cannot be more than {1} characters long.
        /// </summary>
        public static string NameMaxLengthMessage {
            get {
                return ResourceManager.GetString("NameMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The website name chosen is not available.
        /// </summary>
        public static string NameNotAvailableMessage {
            get {
                return ResourceManager.GetString("NameNotAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string NameRequiredMessage {
            get {
                return ResourceManager.GetString("NameRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No websites found.
        /// </summary>
        public static string NoWebsMessage {
            get {
                return ResourceManager.GetString("NoWebsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View {0}.
        /// </summary>
        public static string ReadWebActionLabel {
            get {
                return ResourceManager.GetString("ReadWebActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string ReadWebTabLabel {
            get {
                return ResourceManager.GetString("ReadWebTabLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Websites.
        /// </summary>
        public static string SearchWebsBreadcrumbLabel {
            get {
                return ResourceManager.GetString("SearchWebsBreadcrumbLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a template.
        /// </summary>
        public static string SelectTemplateLabel {
            get {
                return ResourceManager.GetString("SelectTemplateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string TemplateLabel {
            get {
                return ResourceManager.GetString("TemplateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template is required.
        /// </summary>
        public static string TemplateRequiredMessage {
            get {
                return ResourceManager.GetString("TemplateRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0}.
        /// </summary>
        public static string UpdateWebActionLabel {
            get {
                return ResourceManager.GetString("UpdateWebActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Website.
        /// </summary>
        public static string UpdateWebButtonLabel {
            get {
                return ResourceManager.GetString("UpdateWebButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateWebTabLabel {
            get {
                return ResourceManager.GetString("UpdateWebTabLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Uniform Resource Identifier (URI), such as http://www.yourdomain.com, is required to create a website.
        /// </summary>
        public static string UrlRequiredMessage {
            get {
                return ResourceManager.GetString("UrlRequiredMessage", resourceCulture);
            }
        }
    }
}
